# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import chimera_pb2 as chimera__pb2


class BrainStub(object):
    """The Brain Service (Python)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessVision = channel.unary_unary(
                '/chimera.Brain/ProcessVision',
                request_serializer=chimera__pb2.ProcessVisionRequest.SerializeToString,
                response_deserializer=chimera__pb2.VisionResponse.FromString,
                )
        self.QueryMemory = channel.unary_unary(
                '/chimera.Brain/QueryMemory',
                request_serializer=chimera__pb2.QueryMemoryRequest.SerializeToString,
                response_deserializer=chimera__pb2.MemoryResponse.FromString,
                )
        self.UpdateWorldModel = channel.unary_unary(
                '/chimera.Brain/UpdateWorldModel',
                request_serializer=chimera__pb2.WorldModelUpdate.SerializeToString,
                response_deserializer=chimera__pb2.WorldModelResponse.FromString,
                )


class BrainServicer(object):
    """The Brain Service (Python)
    """

    def ProcessVision(self, request, context):
        """Process screenshot with VLM
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryMemory(self, request, context):
        """Query Hive Mind memory
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateWorldModel(self, request, context):
        """Update world model
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BrainServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessVision': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessVision,
                    request_deserializer=chimera__pb2.ProcessVisionRequest.FromString,
                    response_serializer=chimera__pb2.VisionResponse.SerializeToString,
            ),
            'QueryMemory': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryMemory,
                    request_deserializer=chimera__pb2.QueryMemoryRequest.FromString,
                    response_serializer=chimera__pb2.MemoryResponse.SerializeToString,
            ),
            'UpdateWorldModel': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateWorldModel,
                    request_deserializer=chimera__pb2.WorldModelUpdate.FromString,
                    response_serializer=chimera__pb2.WorldModelResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'chimera.Brain', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Brain(object):
    """The Brain Service (Python)
    """

    @staticmethod
    def ProcessVision(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/chimera.Brain/ProcessVision',
            chimera__pb2.ProcessVisionRequest.SerializeToString,
            chimera__pb2.VisionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def QueryMemory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/chimera.Brain/QueryMemory',
            chimera__pb2.QueryMemoryRequest.SerializeToString,
            chimera__pb2.MemoryResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateWorldModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/chimera.Brain/UpdateWorldModel',
            chimera__pb2.WorldModelUpdate.SerializeToString,
            chimera__pb2.WorldModelResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class BodyStub(object):
    """The Body Service (Rust)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExecuteMission = channel.unary_unary(
                '/chimera.Body/ExecuteMission',
                request_serializer=chimera__pb2.MissionRequest.SerializeToString,
                response_deserializer=chimera__pb2.MissionResponse.FromString,
                )
        self.ValidateStealth = channel.unary_unary(
                '/chimera.Body/ValidateStealth',
                request_serializer=chimera__pb2.StealthValidationRequest.SerializeToString,
                response_deserializer=chimera__pb2.StealthValidationResponse.FromString,
                )
        self.GetWorkerStatus = channel.unary_unary(
                '/chimera.Body/GetWorkerStatus',
                request_serializer=chimera__pb2.WorkerStatusRequest.SerializeToString,
                response_deserializer=chimera__pb2.WorkerStatusResponse.FromString,
                )


class BodyServicer(object):
    """The Body Service (Rust)
    """

    def ExecuteMission(self, request, context):
        """Execute browser mission
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateStealth(self, request, context):
        """Validate stealth (CreepJS)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWorkerStatus(self, request, context):
        """Get worker status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BodyServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExecuteMission': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteMission,
                    request_deserializer=chimera__pb2.MissionRequest.FromString,
                    response_serializer=chimera__pb2.MissionResponse.SerializeToString,
            ),
            'ValidateStealth': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateStealth,
                    request_deserializer=chimera__pb2.StealthValidationRequest.FromString,
                    response_serializer=chimera__pb2.StealthValidationResponse.SerializeToString,
            ),
            'GetWorkerStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWorkerStatus,
                    request_deserializer=chimera__pb2.WorkerStatusRequest.FromString,
                    response_serializer=chimera__pb2.WorkerStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'chimera.Body', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Body(object):
    """The Body Service (Rust)
    """

    @staticmethod
    def ExecuteMission(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/chimera.Body/ExecuteMission',
            chimera__pb2.MissionRequest.SerializeToString,
            chimera__pb2.MissionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ValidateStealth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/chimera.Body/ValidateStealth',
            chimera__pb2.StealthValidationRequest.SerializeToString,
            chimera__pb2.StealthValidationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetWorkerStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/chimera.Body/GetWorkerStatus',
            chimera__pb2.WorkerStatusRequest.SerializeToString,
            chimera__pb2.WorkerStatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class GeneralStub(object):
    """The General Service (Node.js)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessLead = channel.unary_unary(
                '/chimera.General/ProcessLead',
                request_serializer=chimera__pb2.LeadRequest.SerializeToString,
                response_deserializer=chimera__pb2.LeadResponse.FromString,
                )
        self.GetEnrichmentStatus = channel.unary_unary(
                '/chimera.General/GetEnrichmentStatus',
                request_serializer=chimera__pb2.StatusRequest.SerializeToString,
                response_deserializer=chimera__pb2.StatusResponse.FromString,
                )


class GeneralServicer(object):
    """The General Service (Node.js)
    """

    def ProcessLead(self, request, context):
        """Request lead processing
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEnrichmentStatus(self, request, context):
        """Get enrichment status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GeneralServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessLead': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessLead,
                    request_deserializer=chimera__pb2.LeadRequest.FromString,
                    response_serializer=chimera__pb2.LeadResponse.SerializeToString,
            ),
            'GetEnrichmentStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEnrichmentStatus,
                    request_deserializer=chimera__pb2.StatusRequest.FromString,
                    response_serializer=chimera__pb2.StatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'chimera.General', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class General(object):
    """The General Service (Node.js)
    """

    @staticmethod
    def ProcessLead(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/chimera.General/ProcessLead',
            chimera__pb2.LeadRequest.SerializeToString,
            chimera__pb2.LeadResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetEnrichmentStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/chimera.General/GetEnrichmentStatus',
            chimera__pb2.StatusRequest.SerializeToString,
            chimera__pb2.StatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
